---
- name: Create config files
  hosts: servers
  become: true
  tasks:
  - name: Create dir
    file:
      path: '{{ config_dir }}/monitoring'
      state: directory
    when: monitoring_prometheus is defined
  - name: Render prometheus config files
    template:
      src: 'config/monitoring/{{ item }}'
      dest: '{{ config_dir }}/monitoring/{{ item }}'
    with_items:
    - prometheus.yml
    when: monitoring_prometheus is defined

- name: Setup Monitoring Docker Node Labels
  hosts: servers
  become: true
  tasks:
  - name: Set monitoring_prometheus and monitoring_grafana node label
    docker_node:
      hostname: '{{ hostvars.get(item).ansible_hostname }}'
      labels:
        monitoring_prometheus: '{{ hostvars.get(item).get("monitoring_prometheus", "false") }}'
        monitoring_grafana: '{{ hostvars.get(item).get("monitoring_grafana", "false") }}'
    run_once: true
    when: docker_swarm_manager_host is defined
    with_items: '{{ play_hosts }}'

- name: Setup network
  hosts: servers
  become: true
  tasks:
  - name: Create monitoring network
    docker_network:
      name: monitoring
      attachable: true
      driver: overlay
    when: docker_swarm_manager_host is defined
    run_once: true

- name: Deploy stack
  hosts: servers
  become: true
  tasks:
  - name: Select Stack Deploy Host
    set_fact:
      stack_deploy_host: true
    run_once: true
    delegate_to: '{{ inventory_hostname }}'
    delegate_facts: true
  - name: Create monitoring.yml temporary file
    tempfile: {}
    register: monitoring_file
    when: stack_deploy_host is defined
    run_once: true
  - name: Create monitoring.yml
    template:
      src: monitoring.stack.yml
      dest: '{{ monitoring_file.path }}'
    when: stack_deploy_host is defined
    run_once: true
  - name: Deploy stack
    docker_stack:
      state: present
      name: monitoring
      compose:
        - '{{ monitoring_file.path }}'
    when: stack_deploy_host is defined
    run_once: true
