---
- name: Create config files
  hosts: servers
  become: true
  tasks:
  - name: Create psono dir
    file:
      path: '{{ config_dir }}/psono'
      state: directory
  - name: Create psono/client dir
    file:
      path: '{{ config_dir }}/psono/client'
      state: directory
  - name: Render psono config files
    template:
      src: 'config/psono/{{ item }}'
      dest: '{{ config_dir }}/psono/{{ item }}'
    with_items:
    - settings.yaml
    - client/config.json

- name: Setup Passwords Docker Node Labels
  hosts: servers
  become: true
  tasks:
  - name: Set passwords_db_mode node label
    docker_node:
      hostname: '{{ hostvars.get(item).ansible_hostname }}'
      labels:
        passwords_db_mode: '{{ hostvars.get(item).get("passwords_db_mode", "unset") }}'
    run_once: true
    when: docker_swarm_manager_host is defined
    with_items: '{{ play_hosts }}'

- name: Deploy stack
  hosts: servers
  become: true
  tasks:
  - name: Select Stack Deploy Host
    set_fact:
      stack_deploy_host: true
    run_once: true
    delegate_to: '{{ inventory_hostname }}'
    delegate_facts: true
  - name: Create passwords.stack.yml temporary file
    tempfile: {}
    register: passwords_file
    when: stack_deploy_host is defined
    run_once: true
  - name: Create passwords.stack.yml
    template:
      src: passwords.stack.yml
      dest: '{{ passwords_file.path }}'
    when: stack_deploy_host is defined
    run_once: true
  - name: Deploy stack
    docker_stack:
      state: present
      name: passwords
      compose:
        - '{{ passwords_file.path }}'
    when: stack_deploy_host is defined
    run_once: true
