services:
  haproxy:
    image: haproxy:latest
    ports:
    - target: 80
      published: 80
      mode: host
    - target: 443
      published: 443
      mode: host
    networks:
    - default
    - lb
    - monitoring
    volumes:
    - {{ config_dir }}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    - {{ certs_dir }}:/usr/local/etc/haproxy/certs:ro
    deploy:
      mode: global
      labels:
        metrics_job: haproxy
        metrics_port: 9090

networks:
  lb:
    name: lb
    external: true
  monitoring:
    name: monitoring
    external: true
