services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
    - prometheus-data:/prometheus
    - {{ config_dir }}/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - {{ docker_certs_dir }}:/docker-certs:ro
    networks:
    - default
    - lb
    - monitoring
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.monitoring_prometheus == true
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
    - '--path.rootfs=/host'
    - '--collector.systemd'
    - '--collector.processes'
    network_mode: host
    pid: host
    volumes:
    - /:/host:ro,rslave
    networks:
    - default
    - monitoring
    deploy:
      mode: global
      labels:
        metrics_job: node-exporter
        metrics_port: 9100
  grafana:
    image: grafana/grafana:latest
    volumes:
    - grafana-data:/var/lib/grafana
    networks:
    - default
    - lb
    environment:
      GF_SERVER_DOMAIN: grafana.monitoring.{{ roll_subdomain_base }}
      GF_SERVER_ROOT_URL: https://grafana.monitoring.{{ roll_subdomain_base }}
      GF_SMTP_ENABLED: 'true'
      GF_SMTP_HOST: smtp:25
      GF_SMTP_FROM_ADDRESS: no-reply@monitoring.{{ roll_servers_domain }}
      GF_SMTP_FROM_NAME: roll monitoring grafana
      GF_AUTH_GENERIC_OAUTH_ENABLED: 'true'
      GF_AUTH_GENERIC_OAUTH_NAME: roll
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: '{{ grafana_oauth2_client_id }}'
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: '{{ grafana_oauth2_client_secret }}'
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://{{ roll_subdomain_base }}/oauth2/authorize/
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://{{ roll_subdomain_base }}/oauth2/token/
      GF_AUTH_GENERIC_OAUTH_API_URL: https://{{ roll_subdomain_base }}/oauth2/userinfo/
      GF_AUTH_GENERIC_OAUTH_SCOPES: 'openid grafana'
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: grafana_email
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: grafana_role
      GF_AUTH_BASIC_ENABLED: 'false'
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_NAME: 'roll'
      GF_AUTH_ANONYMOUS_ORG_ROLE: 'Viewer'
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.monitoring_grafana == true
  smtp:
    image: bytemark/smtp:latest
    environment:
      MAILNAME: monitoring.{{ roll_servers_domain }}
    deploy:
      replicas: 1

volumes:
  prometheus-data: {}
  grafana-data: {}

networks:
  monitoring:
    name: monitoring
    external: true
  lb:
    name: lb
    external: true
