services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
    - prometheus-data:/prometheus
    - {{ config_dir }}/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - {{ docker_certs_dir }}:/docker-certs:ro
    networks:
    - default
    - lb
    - monitoring
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.monitoring_prometheus == true
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
    - '--path.rootfs=/host'
    - '--collector.systemd'
    - '--collector.processes'
    network_mode: host
    pid: host
    volumes:
    - /:/host:ro,rslave
    networks:
    - default
    - monitoring
    deploy:
      mode: global
      labels:
        metrics_job: node-exporter
        metrics_port: 9100
  grafana:
    image: grafana/grafana:latest
    volumes:
    - grafana-data:/var/lib/grafana
    networks:
    - default
    - lb
    environment:
      GF_SERVER_DOMAIN: grafana.monitoring.{{ roll_subdomain_base }}
      GF_SERVER_ROOT_URL: https://grafana.monitoring.{{ roll_subdomain_base }}
      GF_SMTP_ENABLED: 'true'
      GF_SMTP_HOST: smtp:25
      GF_SMTP_FROM_ADDRESS: no-reply@monitoring.{{ roll_subdomain_base }}
      GF_SMTP_FROM_NAME: roll monitoring grafana
      GF_AUTH_GENERIC_OAUTH_ENABLED: 'true'
      GF_AUTH_GENERIC_OAUTH_NAME: roll
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: swnVeT4hKR40iXH5k0oZxUCGOv4PGJ5KDRh736tM
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: k8Y361fT5cxJqj8eduAgZruhmMZQHNlDtfADdJ94HYlAuIcNS08fqm6CuuCvUxLFjN53hRUwTjPuv3LgECHXSIjFg6NHJjuKelLRA9ekLq4fPFopqY59ZeXvQtk8fuBS
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: https://{{ roll_subdomain_base }}/oauth2/authorize
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: https://{{ roll_subdomain_base }}/oauth2/token
      GF_AUTH_GENERIC_OAUTH_API_URL: https://{{ roll_subdomain_base }}/oauth2/userinfo
      GF_AUTH_GENERIC_OAUTH_USE_PKCE: 'true'
      GF_AUTH_GENERIC_OAUTH_SCOPES: openid
      GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: grafana.email
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: grafana.role
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.monitoring_grafana == true
  smtp:
    image: bytemark/smtp:latest
    environment:
      MAILNAME: monitoring.{{ roll_subdomain_base }}
    deploy:
      replicas: 1

volumes:
  prometheus-data: {}
  grafana-data: {}

networks:
  monitoring:
    name: monitoring
    external: true
  lb:
    name: lb
    external: true
