services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
    - prometheus-data:/prometheus
    - {{ config_dir }}/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - {{ docker_certs_dir }}:/docker-certs:ro
    networks:
    - default
    - lb
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.monitoring_prometheus == true
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
    - '--path.rootfs=/host'
    - '--collector.systemd'
    - '--collector.processes'
    network_mode: host
    pid: host
    volumes:
    - /:/host:ro,rslave
    deploy:
      mode: global
      labels:
        metrics_job: node-exporter
        metrics_port: 9100
  grafana:
    image: grafana/grafana:latest
    volumes:
    - grafana-data:/var/lib/grafana
    networks:
    - default
    - lb
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.monitoring_grafana == true

volumes:
  prometheus-data: {}
  grafana-data: {}

networks:
  lb:
    name: lb
    external: true
