services:
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - prometheus-data:/prometheus
    - {{ config_dir }}/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - {{ docker_certs_dir }}:/docker-certs:ro
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.monitoring_prometheus == true
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
    - /:/host:ro,rslave
    deploy:
      mode: global
      labels:
        metrics_job: node-exporter
        metrics_port: 9100

volumes:
  prometheus-data: {}
