services:
  db:
    image: postgres:latest
    volumes:
    - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: roll-passwords
      POSTGRES_PASSWORD: roll-passwords
      POSTGRES_DB: roll-passwords
    command:
      - --wal_level=replica
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.labels.passwords_db_mode == primary

  psono:
    image: psono/psono-combo-enterprise
    volumes:
    - {{ config_dir }}/psono/settings.yaml:/root/.psono_server/settings.yaml
    - {{ config_dir }}/psono/client/config.json:/usr/share/nginx/html/config.json
    - {{ config_dir }}/psono/client/config.json:/usr/share/nginx/html/portal/config.json
    networks:
    - default
    - lb

  smtp:
    image: bytemark/smtp:latest
    environment:
      MAILNAME: passwords.{{ roll_servers_domain }}
    deploy:
      replicas: 1

volumes:
  db-data: {}

networks:
  lb:
    name: lb
    external: true
