name: Play Docker

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4
    - name: Create docker certs dir
      run: mkdir docker-certs
    - name: Create ca.pem
      uses: "DamianReeves/write-file-action@master"
      with:
        path: docker-certs/ca.pem
        contents: ${{secrets.DOCKER_CERT_CA_PEM}}
    - name: Create vps-16507529.servers.r.oll.world.server-cert.pem
      uses: "DamianReeves/write-file-action@master"
      with:
        path: docker-certs/vps-16507529.servers.r.oll.world.server-cert.pem
        contents: ${{secrets.DOCKER_CERT_VPS_16507529_SERVER_CERT_PEM}}
    - name: Create server-key.pem
      uses: "DamianReeves/write-file-action@master"
      with:
        path: docker-certs/server-key.pem
        contents: ${{secrets.DOCKER_CERT_SERVER_KEY_PEM}}
    - name: Create cert.pem
      uses: "DamianReeves/write-file-action@master"
      with:
        path: docker-certs/cert.pem
        contents: ${{secrets.DOCKER_CERT_PEM}}
    - name: Create key.pem
      uses: "DamianReeves/write-file-action@master"
      with:
        path: docker-certs/key.pem
        contents: ${{secrets.DOCKER_CERT_KEY_PEM}}
    - name: Run Docker
      uses: dawidd6/action-ansible-playbook@v2
      env:
        DOCKER_CERTS_DIR: /roll/docker/certs
        LOCAL_DOCKER_CERTS_DIR: ${{github.workspace}}/docker-certs
      with:
        playbook: playbook/docker.yml
        key: ${{secrets.SSH_PRIVATE_KEY}}
        options: |
          -e @variables.yml
          -i inventories/inventory.yml
        known_hosts: |
          vps-16507529.servers.r.oll.world ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMJ9uWhbqfUmpQC97ltAAbdWl9GpAoK4OllCTWenHnEX
          vps-9d706477.servers.r.oll.world ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILBTNlvFsORskMPS4wkK1ha3zqiFEe7CYk+qzxyw08oT
          vps-acf71116.servers.r.oll.world ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID8tAXxIN5OvimPRcz7xWhhQWwy8ThtaWqP4Arp5dfq2

