name: Play LB

on: workflow_dispatch

jobs:
  lb:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Create certs dir
      run: mkdir certs
    - name: Create SSL PEM
      uses: "DamianReeves/write-file-action@master"
      with:
        path: certs/ssl.pem
        contents: ${{secrets.SSL_PEM}}
    - name: Run LB
      uses: dawidd6/action-ansible-playbook@v2
      env:
        LOCAL_CERTS_DIR: ${{github.workspace}}/certs
        ROLL_SERVERS_DOMAIN: ${{vars.ROLL_SERVERS_DOMAIN}}
        ROLL_SUBDOMAIN_BASE: ${{vars.ROLL_SUBDOMAIN_BASE}}
        CONFIG_DIR: /roll/config
        CERTS_DIR: /roll/certs
      with:
        playbook: playbook/lb.yml
        key: ${{secrets.SSH_PRIVATE_KEY}}
        options: |
          -e @variables.yml
          -i inventories/inventory.yml
        known_hosts: |
          vps-16507529.servers.r.oll.world ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMJ9uWhbqfUmpQC97ltAAbdWl9GpAoK4OllCTWenHnEX
          vps-9d706477.servers.r.oll.world ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILBTNlvFsORskMPS4wkK1ha3zqiFEe7CYk+qzxyw08oT
          vps-acf71116.servers.r.oll.world ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID8tAXxIN5OvimPRcz7xWhhQWwy8ThtaWqP4Arp5dfq2
