name: Play Monitoring

on: workflow_dispatch

jobs:
  monitoring:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4
    - name: Create docker-certs dir
      run: mkdir docker-certs
    - name: Create ca.pem
      uses: "DamianReeves/write-file-action@master"
      with:
        path: docker-certs/ca.pem
        contents: ${{secrets.DOCKER_CERT_CA_PEM}}
    - name: Create cert.pem
      uses: "DamianReeves/write-file-action@master"
      with:
        path: docker-certs/cert.pem
        contents: ${{secrets.DOCKER_CERT_PEM}}
    - name: Create key.pem
      uses: "DamianReeves/write-file-action@master"
      with:
        path: docker-certs/key.pem
        contents: ${{secrets.DOCKER_CERT_KEY_PEM}}
    - name: Run Monitoring
      uses: dawidd6/action-ansible-playbook@v2
      env:
        LOCAL_DOCKER_CERTS_DIR: ${{github.workspace}}/docker-certs
        DOCKER_CERTS_DIR: ${{vars.DOCKER_CERTS_DIR}}
        CONFIG_DIR: ${{vars.CONFIG_DIR}}
        ROLL_SUBDOMAIN_BASE: ${{vars.ROLL_SUBDOMAIN_BASE}}
      with:
        playbook: playbook/monitoring.yml
        key: ${{secrets.SSH_PRIVATE_KEY}}
        options: |
          -e @variables.yml
          -i inventories/inventory.yml
        known_hosts: |
          vps-16507529.servers.r.oll.world ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMJ9uWhbqfUmpQC97ltAAbdWl9GpAoK4OllCTWenHnEX
          vps-9d706477.servers.r.oll.world ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGVbM5pfoG8fudLH2C02l3Zn+XO/ub4qwymZhQXD0ktO
          vps-acf71116.servers.r.oll.world ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID8tAXxIN5OvimPRcz7xWhhQWwy8ThtaWqP4Arp5dfq2

